#!/bin/bash
# Claude Mind Manager — Stop Hook (Auto-Save + Learnings + Summary + Periodic Backup)
# Saves active context on EVERY response (overwrite, no growth).
# Extracts learnings every N messages, session summaries every 2N messages.
# Creates periodic backups (incl. transcript) every BACKUP_INTERVAL messages.
# Counter is per session_id (not per project) to handle Desktop chat switching.
# Cost: zero API calls — pure file operations (~50ms).

source "$(dirname "$0")/lib.sh"
mind_init "auto-save-context"

if [ -z "$PROJECT_DIR" ] || [ -z "$TRANSCRIPT_PATH" ]; then
  exit 0
fi

# --- Configurable ---
LEARNINGS_INTERVAL="${MIND_LEARNINGS_INTERVAL:-10}"
CONTEXT_MAX_BYTES="${MIND_CONTEXT_MAX_BYTES:-8000}"
CONTEXT_TAIL_LINES="${MIND_CONTEXT_TAIL_LINES:-150}"
BACKUP_INTERVAL="${MIND_BACKUP_INTERVAL:-10}"

# --- Read message counter ---
COUNT=$(read_counter)

# --- Extract context from transcript (ALWAYS) ---
RAW_CONTEXT=$(extract_assistant_text "$TRANSCRIPT_PATH" "$CONTEXT_TAIL_LINES" "$CONTEXT_MAX_BYTES")

if [ -z "$RAW_CONTEXT" ]; then
  mind_log WARN "no context extracted from transcript"
  exit 0
fi

# --- Collect recent learnings for inclusion in active-context ---
LEARNINGS_SRC="$PROJECT_DIR/.claude-mind/learnings"
RECENT_LEARNINGS=""
if [ -d "$LEARNINGS_SRC" ]; then
  RECENT_LEARNINGS=$(ls -t "$LEARNINGS_SRC"/session-*.md 2>/dev/null | head -3 | \
    xargs -I{} grep -h '^\- ' {} 2>/dev/null | tail -5)
fi

# --- Write active-context.md (EVERY response — overwrites, no growth) ---
RULES_DIR="$PROJECT_DIR/.claude/rules"
mkdir -p "$RULES_DIR"
CONTEXT_FILE="$RULES_DIR/active-context.md"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

cat > "$CONTEXT_FILE" <<CTXEOF
# Active Context — auto-generated by Claude Mind Manager
# Last updated: ${TIMESTAMP} | Message: ${COUNT}
# DO NOT EDIT MANUALLY — overwritten after every Claude response.

## Current Session Extract

${RAW_CONTEXT}

## Recent Learnings

${RECENT_LEARNINGS:-No learnings recorded yet.}
CTXEOF

mind_log "context saved (${#RAW_CONTEXT} bytes, msg ${COUNT})"

# === Below: periodic tasks (only every N messages) ===

if [ "$COUNT" -lt 1 ]; then
  exit 0
fi

MIND_DIR="$PROJECT_DIR/.claude-mind"

# --- Periodic backup (every BACKUP_INTERVAL messages) ---
if [ $((COUNT % BACKUP_INTERVAL)) -eq 0 ]; then
  BACKED_UP=$(create_backup "$PROJECT_DIR" "$TRANSCRIPT_PATH")
  mind_log "backup triggered (msg ${COUNT}, ${BACKED_UP} files)"
  if [ "$BACKED_UP" -gt 0 ]; then
    echo "[Mind Manager] Periodic backup: ${BACKED_UP} file(s) saved (message ${COUNT})"
  fi
fi

# --- Session summary (every MIND_SUMMARY_INTERVAL messages, default 20) ---
SUMMARY_INTERVAL="${MIND_SUMMARY_INTERVAL:-20}"
if [ $((COUNT % SUMMARY_INTERVAL)) -eq 0 ]; then
  write_session_summary "$PROJECT_DIR" "$TRANSCRIPT_PATH" "$COUNT" "$CONTEXT_TAIL_LINES" >/dev/null
  mind_log "summary written (msg ${COUNT})"
fi

# --- Extract learnings (every N messages) ---
if [ $((COUNT % LEARNINGS_INTERVAL)) -eq 0 ]; then
  LEARNINGS_DIR="$MIND_DIR/learnings"
  mkdir -p "$LEARNINGS_DIR"

  TODAY=$(date '+%Y-%m-%d')
  LEARNINGS_FILE="$LEARNINGS_DIR/session-${TODAY}.md"

  LEARNINGS=$(extract_learnings "$TRANSCRIPT_PATH" "$CONTEXT_TAIL_LINES")

  if [ -n "$LEARNINGS" ]; then
    if [ ! -f "$LEARNINGS_FILE" ]; then
      cat > "$LEARNINGS_FILE" <<LEOF
# Session Learnings — ${TODAY}
# Auto-extracted by Claude Mind Manager (Stop hook)
# Format: Korrektur-Flywheel — corrections and decisions from conversation

LEOF
    fi

    atomic_append "$LEARNINGS_FILE" "## Extract at $(date '+%H:%M:%S') (message ${COUNT})

${LEARNINGS}
"
    mind_log "learnings extracted (msg ${COUNT})"
  fi
fi

exit 0
